---
title: "R Notebook"
output: html_notebook
---

```{r}
install.packages("svglite")

library(ape)
library(ggtree)
library(ggplot2)
library(ggnewscale)
library(phytools)
library(randomcoloR)
library(svglite)
```

```{r}
meta_path <- "/Users/abagavetdinova/Desktop/lab/Astroviridae_database/data/clade_analysis/AVES/Astroviridae_Aves_30042026_clusters_shorter.csv"

all_meta <- read.csv(meta_path, sep = ";", stringsAsFactors = FALSE, check.names = FALSE)

fix_na <- function(x) {
  x[is.na(x)] <- "NA"
  x
}

all_meta$aa83_1B <- fix_na(all_meta$aa83_1B)
all_meta$aa90_1B <- fix_na(all_meta$aa90_1B)
all_meta$nt86_1B <- fix_na(all_meta$nt86_1B)
all_meta$nt80_1B <- fix_na(all_meta$nt80_1B)
all_meta$Host_shorter <- fix_na(trimws(all_meta$Host_shorter))

levels_f1 <- sort(unique(all_meta$aa83_1B))
levels_f2 <- sort(unique(all_meta$aa90_1B))
levels_f3 <- sort(unique(all_meta$nt86_1B))
levels_f4 <- sort(unique(all_meta$nt80_1B))

set.seed(123)

make_map <- function(levels) {
  cols <- distinctColorPalette(length(levels))
  setNames(cols, levels)
}

color_map_f1 <- make_map(levels_f1)
color_map_f2 <- make_map(levels_f2)
color_map_f3 <- make_map(levels_f3)
color_map_f4 <- make_map(levels_f4)

bird_colors <- c(
  "Anatidae (утиные)" = "#F4D35E",
  "Phasianidae (фазановые)" = "#800080",
  "Columbidae (голубиные)" = "#71A9F7",
  "Corvidae (врановые)" = "#380036",
  "Passeridae (воробьиные)" = "#0CBABA",
  "Scolopacidae (бекасовые)" = "#C7F2A7",
  "Paridae (синицевые)" = "#D9D0DE",
  "Prunellidae (завирушковые)" = "#800000",
  "Petroicidae (австралийские малиновки)" = "#F40076",
  "Recurvirostridae (шилоклювковые)" = "#FFA630",
  "Cacatuidae (какаду)" = "#380036",
  "Psittacidae (попугаевые)" = "#1C6E8C",
  "Gruidae (журавлиные)" = "#FFAFF0",
  "Acanthizidae (шипоклювковые)" = "#88B7B5",
  "Rhipiduridae (веерохвостковые)" = "#4B0082"
)

manual_host_colors <- c(
  "Mammalia (Млекопитающие)" = "#F8333C",
  "Reptilia (Пресмыкающиеся)" = "#0A2472",
  "Amphibia (Амфибии)" = "#06BA63",
  bird_colors
)

host_order <- c(
  "Mammalia (Млекопитающие)",
  "Reptilia (Пресмыкающиеся)",
  "Amphibia (Амфибии)",
  names(bird_colors),
  "Other"
)
plot_annotated_tree_clusters <- function(tree_file, meta_file, title = "Tree") {
  
  tree <- read.tree(tree_file)
  tree$edge.length[is.na(tree$edge.length)] <- 0
  
  tree$tip.label <- trimws(sapply(strsplit(tree$tip.label, "/"), `[`, 1))
  
  tree_rooted <- midpoint.root(tree)
  
  info <- read.csv(meta_file, sep = ";", stringsAsFactors = FALSE, check.names = FALSE)
  colnames(info) <- gsub(" ", "", colnames(info))
  
  info$id <- trimws(info$id)
  
  fix_na <- function(x) { x[is.na(x)] <- "NA"; x }
  
  info$aa83_1B <- fix_na(info$aa83_1B)
  info$aa90_1B <- fix_na(info$aa90_1B)
  info$nt86_1B <- fix_na(info$nt86_1B)
  info$nt80_1B <- fix_na(info$nt80_1B)
  
  info$Host <- trimws(info$Host_shorter)
  info$Host <- gsub("\\s+", " ", info$Host)
  info$Host <- fix_na(info$Host)
  
  info$sequence_nm[is.na(info$sequence_nm)] <- "unknown"
  
highlight_ids <- c(
  "NC_002470","Y15936","PP623814","NC_005790","AB033998",
    "MN732559","MZ150559","ON964512","MW684819","MW684818","HQ889774",
  "MW684825","MW684833","MW684826","PV093022","OM469230","HM029238",
  "PP871808","PP871786","OQ685945","MT585644","OM469232","MT585643",
  "MW684829","MW684822","MN732558","PP871798",
  "EU143843","EU143844","EU143846","EU143847",
  "EU143848","EU143849","EU143850","EU143851",
    "PV093018"
)

info$label_color <- ifelse(info$id %in% highlight_ids, info$id, "other")

highlight_colors <- c(
  # старые
  "NC_002470" = "#FF0000",
  "Y15936" = "#FF0000",
  "PP623814" = "#00BFC4",
  "NC_005790" = "#00FF00",
  "AB033998" = "#C77CFF",
  "MN732559" = "#C77CFF",
  "MZ150559" = "#C77CFF",
  "ON964512" = "#C77CFF",
  "MW684819" = "#C77CFF",
  "MW684818" = "#C77CFF",
  "HQ889774" = "#C77CFF",
  "MW684825" = "#C77CFF",
  "MW684833" = "#C77CFF",
  "MW684826" = "#C77CFF",
  "PV093022" = "#C77CFF",
  "OM469230" = "#C77CFF",
  "HM029238" = "#C77CFF",
  "PP871808" = "#C77CFF",
  "PP871786" = "#C77CFF",
  "OQ685945" = "#C77CFF",
  "MT585644" = "#C77CFF",
  "OM469232" = "#C77CFF",
  "MT585643" = "#C77CFF",
  "MW684829" = "#C77CFF",
  "MW684822" = "#C77CFF",
  "MN732558" = "#C77CFF",
  "PP871798" = "#C77CFF",
  
  # 00FF00
  "EU143843" = "#00FF00",
  "EU143844" = "#00FF00",
  "EU143846" = "#00FF00",
  "EU143847" = "#00FF00",
  "EU143848" = "#00FF00",
  "EU143849" = "#00FF00",
  "EU143850" = "#00FF00",
  "EU143851" = "#00FF00",
  
  # FF0000
  "PV093018" = "#FF0000",
  
  # default
  "other" = "black"
)
  

  p <- ggtree(tree_rooted, size = 0.7)
  p$data$x <- p$data$x / max(p$data$x)
  p <- p + coord_cartesian(xlim = c(0, 1.5), clip = "off")
  
  df <- p$data
  
  df <- merge(df,
              info[, c("id", "label_color")],
              by.x = "label",
              by.y = "id",
              all.x = TRUE)
  
  df$label_color[is.na(df$label_color)] <- "other"
  
  p$data <- df
  
  df$fontface <- ifelse(df$label_color == "other", "plain", "bold")
  p$data <- df
  
  p <- p +
    #geom_tiplab(
    #  aes(color = label_color, fontface = fontface),
    #  size = 2,
    #  align = FALSE
    #) +
    scale_color_manual(
      values = highlight_colors,
      guide = "none"
    )
  
  # bootstrap
  df <- p$data
  df$bootstrap <- suppressWarnings(as.numeric(df$label))
  p$data <- df
  
  p <- p +
    geom_point2(
      aes(subset = !isTip & !is.na(bootstrap) & bootstrap >= 0.95),
      shape = 21,
      size = 2,
      fill = "black",
      color = "black"
    ) +
    new_scale_fill()
  
  
  cluster_list <- list(
    AA83 = data.frame(AA83 = factor(info$aa83_1B, levels = levels_f1), row.names = info$id),
    AA90 = data.frame(AA90 = factor(info$aa90_1B, levels = levels_f2), row.names = info$id),
    NT86 = data.frame(NT86 = factor(info$nt86_1B, levels = levels_f3), row.names = info$id),
    NT80 = data.frame(NT80 = factor(info$nt80_1B, levels = levels_f4), row.names = info$id)
  )
  
  color_maps <- list(color_map_f1, color_map_f2, color_map_f3, color_map_f4)
  
  info$Host[!info$Host %in% names(manual_host_colors)] <- "Other"
  manual_host_colors["Other"] <- "grey85"
  
  host <- data.frame(
    Host = factor(info$Host, levels = host_order),
    row.names = info$id
  )
  
  base_offset <- 0.18
  width <- 0.07
  step <- 0.07

  p1 <- p
  
  for (i in seq_along(cluster_list)) {
    p1 <- gheatmap(
      p1,
      cluster_list[[i]],
      width = width,
      offset = base_offset + (i - 1) * step,
      colnames = TRUE,
      font.size = 2,
      colnames_position = "top"
    ) +
      scale_fill_manual(
        values = color_maps[[i]],
        guide = "none",
        na.value = "grey90"
      ) +
      theme(axis.text.x = element_blank()) +
      new_scale_fill()
  }
  
  p1 <- gheatmap(
    p1,
    host,
    width = width,
    offset = base_offset + length(cluster_list) * step,
    colnames = TRUE,
    font.size = 2,
    colnames_position = "top"
  ) +
    scale_fill_manual(
      values = manual_host_colors,
      breaks = host_order,
      name = "Хозяин",
      drop = FALSE,
      na.value = "grey85"
    ) +
    theme(axis.text.x = element_blank())
  p1 <- p1 +
  ggtitle(title) +
  theme(
    plot.title = element_text(hjust = 0, size = 10, face = "bold")
  )
  return(p1)
}

```


```{r}
tree_file <- "/Users/abagavetdinova/Desktop/lab/Astroviridae_database/data/clade_analysis/AVES/Aves_1A_removed_97_nt_tree.nwk" 
p <- plot_annotated_tree_clusters(tree_file, meta_path, 'ORF1A (N = 133)')

print(p)

ggsave(
  "/Users/abagavetdinova/Desktop/lab/Astroviridae_database/data/clade_analysis/AVES/nt_1A_tree_97_0809.svg",
  p,
  width = 14,
  height = 10,
  dpi = 300
)
```

```{r}
tree_file <- "/Users/abagavetdinova/Desktop/lab/Astroviridae_database/data/clade_analysis/AVES/Aves_1B_removed_97_nt_tree.nwk" 
p <- plot_annotated_tree_clusters(tree_file, meta_path, 'ORF1B (N = 133)')

print(p)


ggsave(
  "/Users/abagavetdinova/Desktop/lab/Astroviridae_database/data/clade_analysis/AVES/nt_1B_tree_97_0809.svg",
  p,
  width = 14,
  height = 10,
  dpi = 300
)
```

```{r}
tree_file <- "/Users/abagavetdinova/Desktop/lab/Astroviridae_database/data/clade_analysis/AVES/Aves_2_removed_97_nt_tree.nwk" 
p <- plot_annotated_tree_clusters(tree_file, meta_path, 'ORF2 (N = 133)')

print(p)

ggsave(
  "/Users/abagavetdinova/Desktop/lab/Astroviridae_database/data/clade_analysis/AVES/nt_2_tree_97_0809.svg",
  p,
  width = 14,
  height = 10,
  dpi = 300
)
```



```{r}
tree_file <- "/Users/abagavetdinova/Desktop/lab/Astroviridae_database/data/clade_analysis/AVES/Aves_full_seq_removed_1A_align.nwk" 
p <- plot_annotated_tree_clusters(tree_file, meta_path, 'ORF1A')

print(p)

ggsave(
  "/Users/abagavetdinova/Desktop/lab/Astroviridae_database/data/clade_analysis/AVES/nt_1A_full_tree_0305_2.svg",
  p,
  width = 16,
  height = 20,
  dpi = 500
)
```


```{r}
tree_file <- "/Users/abagavetdinova/Desktop/lab/Astroviridae_database/data/clade_analysis/AVES/Aves_full_seq_removed_1B_align.nwk" 
p <- plot_annotated_tree_clusters(tree_file, meta_path, 'ORF1B_full')

print(p)

ggsave(
  "/Users/abagavetdinova/Desktop/lab/Astroviridae_database/data/clade_analysis/AVES/nt_1B_full_tree_0305_2.svg",
  p,
  width = 16,
  height = 20,
  dpi = 500
)
```



```{r}
tree_file <- "/Users/abagavetdinova/Desktop/lab/Astroviridae_database/data/clade_analysis/AVES/Aves_full_seq_removed_2_align.nwk" 
p <- plot_annotated_tree_clusters(tree_file, meta_path, 'ORF2_full')

print(p)

ggsave(
  "/Users/abagavetdinova/Desktop/lab/Astroviridae_database/data/clade_analysis/AVES/nt_2_full_tree_0305_2.svg",
  p,
  width = 16,
  height = 20,
  dpi = 500
)
```